# Generated by Django 3.2.9 on 2022-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20220204_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(upload_to='image/download/'),
        ),
    ]
