# Generated by Django 3.2.9 on 2022-02-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_alter_slidermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(upload_to='pics/%y/%m/%d/'),
        ),
    ]
